# Kích hoạt split + BLE cho nửa phải
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=y   # Nửa phải làm Peripheral (Slave)

# Tắt USB để tránh nhận 2 HID khi cắm cả 2 mạch cùng lúc
CONFIG_ZMK_USB=n
